site_name: Animai-vos!
site_author: Jurandy Soares
site_description: "Documentação do projeto Animai-vos!"
site_url: https://jurandysoares.github.io/animaivos/

repo_url: https://github.com/jurandysoares/animaivos
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt
  features:
    - content.action.edit
    - content.action.view

  icon:
    edit: material/pencil 
    view: material/eye

  palette:
    primary: "blue"
    accent: "light-blue"

markdown_extensions:
  - footnotes
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.smartsymbols

plugins:
  # - git-authors
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://installer.readthedocs.io/en/stable/objects.inv

nav:
  - Início: index.md
  - main:

      - main/index.md
      - main/main.md
      - main/cena4.md
      - main/cena1.md
      - main/cena2.md
      - main/cena3.md
      - main/cena_demo.md

  - animaivos:

    - animaivos/menus.md
    - nucleo:
  
        - animaivos/nucleo/index.md
        - animaivos/nucleo/habilita_clique.md
        - animaivos/nucleo/fala.md
        - animaivos/nucleo/carrega_img_fundo.md
        - animaivos/nucleo/carrega_personagens.md
        - animaivos/nucleo/exibir_coordenadas.md
